modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"
issueTrackerURL="https://github.com/brnbrd/Delightful/issues"

[[mods]]
modId="delightful"
version="${file.jarVersion}"
displayName="Delightful"
displayURL="https://www.curseforge.com/minecraft/mc-mods/delightful"
updateJSONURL="https://raw.githubusercontent.com/brnbrd/Delightful/1.20.1/update/update.json"
logoFile="delightful.png"
logoBlur=false
credits="championhestu (artist), vectorwing"
authors="brnbrd"
description="Farmer's Delight addon with mod compatibility features and fun new foods."
itemIcon="delightful:smore"
configBackground="farmersdelight:textures/block/tatami_mat_half.png"

[[dependencies.delightful]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.delightful]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.20.1-1.2.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="everycomp"
    mandatory=false
    versionRange="[1.20,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="farmersrespite"
    mandatory=false
    versionRange="[1.20.1-2.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="miners_delight"
    mandatory=false
    versionRange="[1.20.1-1.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="rootsclassic"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="ars_nouveau"
    mandatory=false
    versionRange="[4.12,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="create"
    mandatory=false
    versionRange="[0.5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="create_central_kitchen"
    mandatory=false
    versionRange="[1.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="duckling"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="some_assembly_required"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="abnormals_delight"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="neapolitan"
    mandatory=false
    versionRange="[5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="incubation"
    mandatory=false
    versionRange="[4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="autumnity"
    mandatory=false
    versionRange="[5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="upgrade_aquatic"
    mandatory=false
    versionRange="[6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="buzzier_bees"
    mandatory=false
    versionRange="[6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="biomeswevegone"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="undergarden"
    mandatory=false
    versionRange="[0.8,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="undergardendelight"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="spawn"
    mandatory=false
    versionRange="[1.20.1-1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="finsandtails"
    mandatory=false
    versionRange="[1.20.1-1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="naturalist"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="aether"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="deep_aether"
    mandatory=false
    versionRange="[1.20.1-1.0.4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="aether_redux"
    mandatory=false
    versionRange="[2.0.17,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="vampirism"
    mandatory=false
    versionRange="[1.10,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="vampiresdelight"
    mandatory=false
    versionRange="[0.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="fruitsdelight"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="twilightforest"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="twilightdelight"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="twigs"
    mandatory=false
    versionRange="[1.20.1-3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="vintagedelight"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="culturaldelights"
    mandatory=false
    versionRange="[0.16,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="sunflowerdelight"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="moredelight"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="additionaladditions"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="hauntedharvest"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="untameddelight"
    mandatory=false
    versionRange="[1.20.1-1.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="habitat"
    mandatory=false
    versionRange="[1.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="goated"
    mandatory=false
    versionRange="[1.20-1.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="dropthemeat"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"