modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"
issueTrackerURL="https://github.com/brnbrd/Delightful/issues"

[[mods]]
modId="delightful"
version="${file.jarVersion}"
displayName="Delightful"
displayURL="https://www.curseforge.com/minecraft/mc-mods/delightful"
updateJSONURL="https://raw.githubusercontent.com/brnbrd/Delightful/1.19/update/update.json"
logoFile="delightful.png"
logoBlur=false
credits="championhestu (artist), vectorwing"
authors="brnbrd"
description="Farmer's Delight addon with mod compatibility features and fun new foods."
itemIcon="delightful:smore"
configBackground="farmersdelight:textures/block/tatami_mat_half.png"

[[dependencies.delightful]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.delightful]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.20.1-1.2.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="miners_delight"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="rootsclassic"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="ars_nouveau"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="create"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="duckling"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="byg"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="undergarden"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="undergardendelight"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="spawn"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="naturalist"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="aether"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="deep_aether"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="twilightforest"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="twilightdelight"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="vintagedelight"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="sunflowerdelight"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.delightful]]
    modId="additionaladditions"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"